// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2iFU-W05du5bLtIlkS_c15AdA5UY63y0',
    appId: '1:156230325896:web:f95c34213193077524f13d',
    messagingSenderId: '156230325896',
    projectId: 'expense-tracker-app-382ed',
    authDomain: 'expense-tracker-app-382ed.firebaseapp.com',
    storageBucket: 'expense-tracker-app-382ed.firebasestorage.app',
    measurementId: 'G-HH8R0GP3BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYvISV-8tSoOw0lA0xB5j6XKosmPFJG1Y',
    appId: '1:156230325896:android:9a287a897918bee324f13d',
    messagingSenderId: '156230325896',
    projectId: 'expense-tracker-app-382ed',
    storageBucket: 'expense-tracker-app-382ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD76Qw9Ji2dM5Z0PNEtWYx05j2PUgC960Y',
    appId: '1:156230325896:ios:3bb50171ed14a9c324f13d',
    messagingSenderId: '156230325896',
    projectId: 'expense-tracker-app-382ed',
    storageBucket: 'expense-tracker-app-382ed.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD76Qw9Ji2dM5Z0PNEtWYx05j2PUgC960Y',
    appId: '1:156230325896:ios:3bb50171ed14a9c324f13d',
    messagingSenderId: '156230325896',
    projectId: 'expense-tracker-app-382ed',
    storageBucket: 'expense-tracker-app-382ed.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2iFU-W05du5bLtIlkS_c15AdA5UY63y0',
    appId: '1:156230325896:web:a1008e74092cdb5324f13d',
    messagingSenderId: '156230325896',
    projectId: 'expense-tracker-app-382ed',
    authDomain: 'expense-tracker-app-382ed.firebaseapp.com',
    storageBucket: 'expense-tracker-app-382ed.firebasestorage.app',
    measurementId: 'G-7J69C8D8RH',
  );
}
